version: '3'

services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/var/app
    environment:
      REDIS_URL: redis://redis:6379
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
